import { useMemo } from "react";

export function useSettingsModalProps({
  settingsOpen,
  closeSettings,
  settings,
  setSettings,
  dailyTpl,
  setDailyTpl,
  weeklyTpl,
  setWeeklyTpl,
  fbReady,
  user,
  cloudBusy,
  cloudError,
  doSignIn,
  doSignOut,
  hardResetAccount,
  resetCloudAccount,
  profileName,
  setProfileName,
  saveProfileName,
  onCloudPull,
  backupLocalSnapshot,
  restoreCloudFromLocalBackup,
  onEmailSignUp,
  onEmailSignIn,
  staySignedIn,
  setStaySignedInPreference,
}) {
  return useMemo(
    () => ({
      open: settingsOpen,
      onClose: closeSettings,
      settings,
      setSettings,
      dailyTpl,
      setDailyTpl,
      weeklyTpl,
      setWeeklyTpl,
      fbReady,
      user,
      cloudBusy,
      cloudError,
      onSignIn: doSignIn,
      onSignOut: doSignOut,
      onEmailSignUp,
      onEmailSignIn,
      staySignedIn,
      onToggleStaySignedIn: setStaySignedInPreference,
      onResetAccount: hardResetAccount,
      onResetCloud: resetCloudAccount,
      profileName,
      setProfileName,
      onSaveProfileName: saveProfileName,
      onCloudPull,
      onBackupLocal: backupLocalSnapshot,
      onRestoreFromLocalToCloud: restoreCloudFromLocalBackup,
    }),
    [
      settingsOpen,
      closeSettings,
      settings,
      setSettings,
      dailyTpl,
      setDailyTpl,
      weeklyTpl,
      setWeeklyTpl,
      fbReady,
      user,
      cloudBusy,
      cloudError,
      doSignIn,
      doSignOut,
      onEmailSignUp,
      onEmailSignIn,
      staySignedIn,
      setStaySignedInPreference,
      hardResetAccount,
      resetCloudAccount,
      profileName,
      setProfileName,
      saveProfileName,
      onCloudPull,
      backupLocalSnapshot,
      restoreCloudFromLocalBackup,
    ],
  );
}

export function useProfileModalProps({
  profileOpen,
  profileName,
  setProfileName,
  saveProfileName,
  closeProfile,
}) {
  return useMemo(
    () => ({
      open: profileOpen,
      profileName,
      onChangeName: setProfileName,
      onSave: saveProfileName,
      onClose: closeProfile,
    }),
    [profileOpen, profileName, setProfileName, saveProfileName, closeProfile],
  );
}
